name: d4_shape
version: 1.0.0
description: Graphical primitives for visualization, such as lines and areas.
repository: https://github.com/luizbarboza/d4_shape

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  d4_array: ^1.0.0
  d4_path: ^1.0.0
  d4_polygon: ^1.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0